name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [cdp-1.0.0]
  # run it during pull request
  pull_request:  

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build and push to docker.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: export FRAPPE_APPS
        run: |
          echo export var FRAPPE_APPS
          echo "FRAPPE_APPS=$(base64 -w 0 ./.aseno/apps.json)" >> $GITHUB_ENV
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: images/custom/Containerfile
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-14
            PYTHON_VERSION=3.10.5
            NODE_VERSION=16.18.0
            APPS_JSON_BASE64=${{ env.FRAPPE_APPS }}
          # Note: tags has to be all lower-case
          tags: |
            aseno/frappe-erpnext-health:1.0.3 
            aseno/frappe-erpnext-health:latest
          # build on feature branches, push only on release-1.0.0 branch
          push: ${{ github.ref == 'refs/heads/cdp-1.0.0' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
